volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local


services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
     - "9090:9090"
    volumes:
     - /etc/prometheus:/config
     - prometheus-data:/prometheus
    restart: unless-stopped
    command:
     - "--config.file=/config/prometheus.ini"


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3117:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped


#  cadvisor:
#    image: google/cadvisor:latest
#    container_name: cadvisor
    # ports:
    #   - "8080:8080"
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro
#    devices:
#      - /dev/kmsg
#    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter
    container_name: prom_node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
